<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Dtn_Office::css/style.css') ?>" />

<?php $employees = $block->getData('employees'); ?>

<h1>List Employees</h1>
<table border="1px">
    <thead>
        <tr>
            <th>Name</th>
            <th>Image</th>
            <th>Address</th>
            <th>Phone number</th>
            <th>Birth day</th>
            <th>Department</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($employees as $employee): ?>
            <tr>
                <td><?= $employee['full_name']; ?></td>
                <td>
                    <img src="<?= $block->getData('mediaURL') . $employee['image']; ?>" width="100" height="100" />
                </td>
                <td><?= $employee['address']; ?></td>
                <td><?= $employee['telephone']; ?></td>
                <td><?= $employee['dob']; ?></td>
                <td><?= $employee['department_name']; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
